// GENERATED by web/scripts/gen-android-icons.mjs from lucide-react 1.16.0 — do not edit.
// Rerun (from web/: node scripts/gen-android-icons.mjs) after the web app starts using a new icon.
@file:Suppress("unused")

package com.slowatcoding.finio.ui.icons

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.addPathNodes
import androidx.compose.ui.unit.dp
import java.util.concurrent.ConcurrentHashMap

/**
 * Every lucide icon the PWA uses, as 24×24 stroke-based [ImageVector]s (stroke 2, round caps and
 * joins, black so `Icon(tint = …)` recolours them — lucide's `currentColor`).
 *
 * Look icons up by the same kebab-case name the web stores on categories, goals and people
 * ([byKebab]), or use a typed property. A thicker stroke (the active tab's 2.4) is
 * `byKebab(name, strokeWidth = 2.4f)`.
 */
object LucideIcons {
    /** Kebab-case icon name → path data. A leading '!' marks an element lucide also fills. */
    private val data: Map<String, Array<String>> = mapOf(
        "archive" to arrayOf("M3 3h18a1 1 0 0 1 1 1v3a1 1 0 0 1 -1 1h-18a1 1 0 0 1 -1 -1v-3a1 1 0 0 1 1 -1Z", "M4 8v11a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8", "M10 12h4"),
        "arrow-down" to arrayOf("M12 5v14", "m19 12-7 7-7-7"),
        "arrow-left" to arrayOf("m12 19-7-7 7-7", "M19 12H5"),
        "arrow-left-right" to arrayOf("M8 3 4 7l4 4", "M4 7h16", "m16 21 4-4-4-4", "M20 17H4"),
        "arrow-right" to arrayOf("M5 12h14", "m12 5 7 7-7 7"),
        "arrow-up" to arrayOf("m5 12 7-7 7 7", "M12 19V5"),
        "baby" to arrayOf("M10 16c.5.3 1.2.5 2 .5s1.5-.2 2-.5", "M15 12h.01", "M19.38 6.813A9 9 0 0 1 20.8 10.2a2 2 0 0 1 0 3.6 9 9 0 0 1-17.6 0 2 2 0 0 1 0-3.6A9 9 0 0 1 12 3c2 0 3.5 1.1 3.5 2.5s-.9 2.5-2 2.5c-.8 0-1.5-.4-1.5-1", "M9 12h.01"),
        "banknote" to arrayOf("M4 6h16a2 2 0 0 1 2 2v8a2 2 0 0 1 -2 2h-16a2 2 0 0 1 -2 -2v-8a2 2 0 0 1 2 -2Z", "M10 12a2 2 0 1 0 4 0a2 2 0 1 0 -4 0", "M6 12h.01M18 12h.01"),
        "bell" to arrayOf("M10.268 21a2 2 0 0 0 3.464 0", "M3.262 15.326A1 1 0 0 0 4 17h16a1 1 0 0 0 .74-1.673C19.41 13.956 18 12.499 18 8A6 6 0 0 0 6 8c0 4.499-1.411 5.956-2.738 7.326"),
        "bell-ring" to arrayOf("M10.268 21a2 2 0 0 0 3.464 0", "M22 8c0-2.3-.8-4.3-2-6", "M3.262 15.326A1 1 0 0 0 4 17h16a1 1 0 0 0 .74-1.673C19.41 13.956 18 12.499 18 8A6 6 0 0 0 6 8c0 4.499-1.411 5.956-2.738 7.326", "M4 2C2.8 3.7 2 5.7 2 8"),
        "bike" to arrayOf("M15 17.5a3.5 3.5 0 1 0 7 0a3.5 3.5 0 1 0 -7 0", "M2 17.5a3.5 3.5 0 1 0 7 0a3.5 3.5 0 1 0 -7 0", "M14 5a1 1 0 1 0 2 0a1 1 0 1 0 -2 0", "M12 17.5V14l-3-3 4-3 2 3h2"),
        "book-open" to arrayOf("M12 7v14", "M3 18a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h5a4 4 0 0 1 4 4 4 4 0 0 1 4-4h5a1 1 0 0 1 1 1v13a1 1 0 0 1-1 1h-6a3 3 0 0 0-3 3 3 3 0 0 0-3-3z"),
        "bookmark-plus" to arrayOf("M12 7v6", "M15 10H9", "M17 3a2 2 0 0 1 2 2v15a1 1 0 0 1-1.496.868l-4.512-2.578a2 2 0 0 0-1.984 0l-4.512 2.578A1 1 0 0 1 5 20V5a2 2 0 0 1 2-2z"),
        "briefcase" to arrayOf("M16 20V4a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16", "M4 6h16a2 2 0 0 1 2 2v10a2 2 0 0 1 -2 2h-16a2 2 0 0 1 -2 -2v-10a2 2 0 0 1 2 -2Z"),
        "building-2" to arrayOf("M10 12h4", "M10 8h4", "M14 21v-3a2 2 0 0 0-4 0v3", "M6 10H4a2 2 0 0 0-2 2v7a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2h-2", "M6 21V5a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v16"),
        "bus" to arrayOf("M8 6v6", "M15 6v6", "M2 12h19.6", "M18 18h3s.5-1.7.8-2.8c.1-.4.2-.8.2-1.2 0-.4-.1-.8-.2-1.2l-1.4-5C20.1 6.8 19.1 6 18 6H4a2 2 0 0 0-2 2v10h3", "M5 18a2 2 0 1 0 4 0a2 2 0 1 0 -4 0", "M9 18h5", "M14 18a2 2 0 1 0 4 0a2 2 0 1 0 -4 0"),
        "cake" to arrayOf("M20 21v-8a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v8", "M4 16s.5-1 2-1 2.5 2 4 2 2.5-2 4-2 2.5 2 4 2 2-1 2-1", "M2 21h20", "M7 8v3", "M12 8v3", "M17 8v3", "M7 4h.01", "M12 4h.01", "M17 4h.01"),
        "calendar" to arrayOf("M8 2v4", "M16 2v4", "M5 4h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2Z", "M3 10h18"),
        "calendar-clock" to arrayOf("M16 14v2.2l1.6 1", "M16 2v4", "M21 7.5V6a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h3.5", "M3 10h5", "M8 2v4", "M10 16a6 6 0 1 0 12 0a6 6 0 1 0 -12 0"),
        "calendar-range" to arrayOf("M5 4h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2Z", "M16 2v4", "M3 10h18", "M8 2v4", "M17 14h-6", "M13 18H7", "M7 14h.01", "M17 18h.01"),
        "calendar-x" to arrayOf("M8 2v4", "M16 2v4", "M5 4h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2Z", "M3 10h18", "m14 14-4 4", "m10 14 4 4"),
        "camera" to arrayOf("M13.997 4a2 2 0 0 1 1.76 1.05l.486.9A2 2 0 0 0 18.003 7H20a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2h1.997a2 2 0 0 0 1.759-1.048l.489-.904A2 2 0 0 1 10.004 4z", "M9 13a3 3 0 1 0 6 0a3 3 0 1 0 -6 0"),
        "car" to arrayOf("M19 17h2c.6 0 1-.4 1-1v-3c0-.9-.7-1.7-1.5-1.9C18.7 10.6 16 10 16 10s-1.3-1.4-2.2-2.3c-.5-.4-1.1-.7-1.8-.7H5c-.6 0-1.1.4-1.4.9l-1.4 2.9A3.7 3.7 0 0 0 2 12v4c0 .6.4 1 1 1h2", "M5 17a2 2 0 1 0 4 0a2 2 0 1 0 -4 0", "M9 17h6", "M15 17a2 2 0 1 0 4 0a2 2 0 1 0 -4 0"),
        "chart-column" to arrayOf("M3 3v16a2 2 0 0 0 2 2h16", "M18 17V9", "M13 17V5", "M8 17v-3"),
        "chart-line" to arrayOf("M3 3v16a2 2 0 0 0 2 2h16", "m19 9-5 5-4-4-3 3"),
        "check" to arrayOf("M20 6 9 17l-5-5"),
        "chevron-down" to arrayOf("m6 9 6 6 6-6"),
        "chevron-left" to arrayOf("m15 18-6-6 6-6"),
        "chevron-right" to arrayOf("m9 18 6-6-6-6"),
        "chevron-up" to arrayOf("m18 15-6-6-6 6"),
        "circle-alert" to arrayOf("M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0", "M12 8L12 12", "M12 16L12.01 16"),
        "circle-check" to arrayOf("M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0", "m9 12 2 2 4-4"),
        "circle-ellipsis" to arrayOf("M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0", "M17 12h.01", "M12 12h.01", "M7 12h.01"),
        "circle-x" to arrayOf("M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0", "m15 9-6 6", "m9 9 6 6"),
        "clock" to arrayOf("M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0", "M12 6v6l4 2"),
        "cloud" to arrayOf("M17.5 19H9a7 7 0 1 1 6.71-9h1.79a4.5 4.5 0 1 1 0 9Z"),
        "cloud-upload" to arrayOf("M12 13v8", "M4 14.899A7 7 0 1 1 15.71 8h1.79a4.5 4.5 0 0 1 2.5 8.242", "m8 17 4-4 4 4"),
        "coffee" to arrayOf("M10 2v2", "M14 2v2", "M16 8a1 1 0 0 1 1 1v8a4 4 0 0 1-4 4H7a4 4 0 0 1-4-4V9a1 1 0 0 1 1-1h14a4 4 0 1 1 0 8h-1", "M6 2v2"),
        "copy" to arrayOf("M10 8h10a2 2 0 0 1 2 2v10a2 2 0 0 1 -2 2h-10a2 2 0 0 1 -2 -2v-10a2 2 0 0 1 2 -2Z", "M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2"),
        "credit-card" to arrayOf("M4 5h16a2 2 0 0 1 2 2v10a2 2 0 0 1 -2 2h-16a2 2 0 0 1 -2 -2v-10a2 2 0 0 1 2 -2Z", "M2 10L22 10"),
        "database-backup" to arrayOf("M3 5a9 3 0 1 0 18 0a9 3 0 1 0 -18 0", "M3 12a9 3 0 0 0 5 2.69", "M21 9.3V5", "M3 5v14a9 3 0 0 0 6.47 2.88", "M12 12v4h4", "M13 20a5 5 0 0 0 9-3 4.5 4.5 0 0 0-4.5-4.5c-1.33 0-2.54.54-3.41 1.41L12 16"),
        "delete" to arrayOf("M10 5a2 2 0 0 0-1.344.519l-6.328 5.74a1 1 0 0 0 0 1.481l6.328 5.741A2 2 0 0 0 10 19h10a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2z", "m12 9 6 6", "m18 9-6 6"),
        "dollar-sign" to arrayOf("M12 2L12 22", "M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"),
        "download" to arrayOf("M12 15V3", "M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4", "m7 10 5 5 5-5"),
        "droplet" to arrayOf("M12 22a7 7 0 0 0 7-7c0-2-1-3.9-3-5.5s-3.5-4-4-6.5c-.5 2.5-2 4.9-4 6.5C6 11.1 5 13 5 15a7 7 0 0 0 7 7z"),
        "dumbbell" to arrayOf("M17.596 12.768a2 2 0 1 0 2.829-2.829l-1.768-1.767a2 2 0 0 0 2.828-2.829l-2.828-2.828a2 2 0 0 0-2.829 2.828l-1.767-1.768a2 2 0 1 0-2.829 2.829z", "m2.5 21.5 1.4-1.4", "m20.1 3.9 1.4-1.4", "M5.343 21.485a2 2 0 1 0 2.829-2.828l1.767 1.768a2 2 0 1 0 2.829-2.829l-6.364-6.364a2 2 0 1 0-2.829 2.829l1.768 1.767a2 2 0 0 0-2.828 2.829z", "m9.6 14.4 4.8-4.8"),
        "eye" to arrayOf("M2.062 12.348a1 1 0 0 1 0-.696 10.75 10.75 0 0 1 19.876 0 1 1 0 0 1 0 .696 10.75 10.75 0 0 1-19.876 0", "M9 12a3 3 0 1 0 6 0a3 3 0 1 0 -6 0"),
        "eye-off" to arrayOf("M10.733 5.076a10.744 10.744 0 0 1 11.205 6.575 1 1 0 0 1 0 .696 10.747 10.747 0 0 1-1.444 2.49", "M14.084 14.158a3 3 0 0 1-4.242-4.242", "M17.479 17.499a10.75 10.75 0 0 1-15.417-5.151 1 1 0 0 1 0-.696 10.75 10.75 0 0 1 4.446-5.143", "m2 2 20 20"),
        "file-spreadsheet" to arrayOf("M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z", "M14 2v5a1 1 0 0 0 1 1h5", "M8 13h2", "M14 13h2", "M8 17h2", "M14 17h2"),
        "file-up" to arrayOf("M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z", "M14 2v5a1 1 0 0 0 1 1h5", "M12 12v6", "m15 15-3-3-3 3"),
        "film" to arrayOf("M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2Z", "M7 3v18", "M3 7.5h4", "M3 12h18", "M3 16.5h4", "M17 3v18", "M17 7.5h4", "M17 16.5h4"),
        "fingerprint-pattern" to arrayOf("M12 10a2 2 0 0 0-2 2c0 1.02-.1 2.51-.26 4", "M14 13.12c0 2.38 0 6.38-1 8.88", "M17.29 21.02c.12-.6.43-2.3.5-3.02", "M2 12a10 10 0 0 1 18-6", "M2 16h.01", "M21.8 16c.2-2 .131-5.354 0-6", "M5 19.5C5.5 18 6 15 6 12a6 6 0 0 1 .34-2", "M8.65 22c.21-.66.45-1.32.57-2", "M9 6.8a6 6 0 0 1 9 5.2v2"),
        "flame" to arrayOf("M12 3q1 4 4 6.5t3 5.5a1 1 0 0 1-14 0 5 5 0 0 1 1-3 1 1 0 0 0 5 0c0-2-1.5-3-1.5-5q0-2 2.5-4"),
        "folder" to arrayOf("M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z"),
        "folder-open" to arrayOf("m6 14 1.5-2.9A2 2 0 0 1 9.24 10H20a2 2 0 0 1 1.94 2.5l-1.54 6a2 2 0 0 1-1.95 1.5H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h3.9a2 2 0 0 1 1.69.9l.81 1.2a2 2 0 0 0 1.67.9H18a2 2 0 0 1 2 2v2"),
        "fuel" to arrayOf("M14 13h2a2 2 0 0 1 2 2v2a2 2 0 0 0 4 0v-6.998a2 2 0 0 0-.59-1.42L18 5", "M14 21V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v16", "M2 21h13", "M3 9h11"),
        "funnel" to arrayOf("M10 20a1 1 0 0 0 .553.895l2 1A1 1 0 0 0 14 21v-7a2 2 0 0 1 .517-1.341L21.74 4.67A1 1 0 0 0 21 3H3a1 1 0 0 0-.742 1.67l7.225 7.989A2 2 0 0 1 10 14z"),
        "gamepad-2" to arrayOf("M6 11L10 11", "M8 9L8 13", "M15 12L15.01 12", "M18 10L18.01 10", "M17.32 5H6.68a4 4 0 0 0-3.978 3.59c-.006.052-.01.101-.017.152C2.604 9.416 2 14.456 2 16a3 3 0 0 0 3 3c1 0 1.5-.5 2-1l1.414-1.414A2 2 0 0 1 9.828 16h4.344a2 2 0 0 1 1.414.586L17 18c.5.5 1 1 2 1a3 3 0 0 0 3-3c0-1.545-.604-6.584-.685-7.258-.007-.05-.011-.1-.017-.151A4 4 0 0 0 17.32 5z"),
        "gift" to arrayOf("M12 7v14", "M20 11v8a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2v-8", "M7.5 7a1 1 0 0 1 0-5A4.8 8 0 0 1 12 7a4.8 8 0 0 1 4.5-5 1 1 0 0 1 0 5", "M4 7h16a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-16a1 1 0 0 1 -1 -1v-2a1 1 0 0 1 1 -1Z"),
        "graduation-cap" to arrayOf("M21.42 10.922a1 1 0 0 0-.019-1.838L12.83 5.18a2 2 0 0 0-1.66 0L2.6 9.08a1 1 0 0 0 0 1.832l8.57 3.908a2 2 0 0 0 1.66 0z", "M22 10v6", "M6 12.5V16a6 3 0 0 0 12 0v-3.5"),
        "hand-coins" to arrayOf("M11 15h2a2 2 0 1 0 0-4h-3c-.6 0-1.1.2-1.4.6L3 17", "m7 21 1.6-1.4c.3-.4.8-.6 1.4-.6h4c1.1 0 2.1-.4 2.8-1.2l4.6-4.4a2 2 0 0 0-2.75-2.91l-4.2 3.9", "m2 16 6 6", "M13.1 9a2.9 2.9 0 1 0 5.8 0a2.9 2.9 0 1 0 -5.8 0", "M3 5a3 3 0 1 0 6 0a3 3 0 1 0 -6 0"),
        "handshake" to arrayOf("m11 17 2 2a1 1 0 1 0 3-3", "m14 14 2.5 2.5a1 1 0 1 0 3-3l-3.88-3.88a3 3 0 0 0-4.24 0l-.88.88a1 1 0 1 1-3-3l2.81-2.81a5.79 5.79 0 0 1 7.06-.87l.47.28a2 2 0 0 0 1.42.25L21 4", "m21 3 1 11h-2", "M3 3 2 14l6.5 6.5a1 1 0 1 0 3-3", "M3 4h8"),
        "hard-drive" to arrayOf("M10 16h.01", "M2.212 11.577a2 2 0 0 0-.212.896V18a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-5.527a2 2 0 0 0-.212-.896L18.55 5.11A2 2 0 0 0 16.76 4H7.24a2 2 0 0 0-1.79 1.11z", "M21.946 12.013H2.054", "M6 16h.01"),
        "heart" to arrayOf("M2 9.5a5.5 5.5 0 0 1 9.591-3.676.56.56 0 0 0 .818 0A5.49 5.49 0 0 1 22 9.5c0 2.29-1.5 4-3 5.5l-5.492 5.313a2 2 0 0 1-3 .019L5 15c-1.5-1.5-3-3.2-3-5.5"),
        "heart-pulse" to arrayOf("M2 9.5a5.5 5.5 0 0 1 9.591-3.676.56.56 0 0 0 .818 0A5.49 5.49 0 0 1 22 9.5c0 2.29-1.5 4-3 5.5l-5.492 5.313a2 2 0 0 1-3 .019L5 15c-1.5-1.5-3-3.2-3-5.5", "M3.22 13H9.5l.5-1 2 4.5 2-7 1.5 3.5h5.27"),
        "history" to arrayOf("M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8", "M3 3v5h5", "M12 7v5l4 2"),
        "house" to arrayOf("M15 21v-8a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v8", "M3 10a2 2 0 0 1 .709-1.528l7-6a2 2 0 0 1 2.582 0l7 6A2 2 0 0 1 21 10v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"),
        "info" to arrayOf("M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0", "M12 16v-4", "M12 8h.01"),
        "key-round" to arrayOf("M2.586 17.414A2 2 0 0 0 2 18.828V21a1 1 0 0 0 1 1h3a1 1 0 0 0 1-1v-1a1 1 0 0 1 1-1h1a1 1 0 0 0 1-1v-1a1 1 0 0 1 1-1h.172a2 2 0 0 0 1.414-.586l.814-.814a6.5 6.5 0 1 0-4-4z", "!M16 7.5a0.5 0.5 0 1 0 1 0a0.5 0.5 0 1 0 -1 0"),
        "landmark" to arrayOf("M10 18v-7", "M11.119 2.205a2 2 0 0 1 1.762 0l7.84 3.846A.5.5 0 0 1 20.5 7h-17a.5.5 0 0 1-.22-.949z", "M14 18v-7", "M18 18v-7", "M3 22h18", "M6 18v-7"),
        "laptop" to arrayOf("M18 5a2 2 0 0 1 2 2v8.526a2 2 0 0 0 .212.897l1.068 2.127a1 1 0 0 1-.9 1.45H3.62a1 1 0 0 1-.9-1.45l1.068-2.127A2 2 0 0 0 4 15.526V7a2 2 0 0 1 2-2z", "M20.054 15.987H3.946"),
        "layout-dashboard" to arrayOf("M4 3h5a1 1 0 0 1 1 1v7a1 1 0 0 1 -1 1h-5a1 1 0 0 1 -1 -1v-7a1 1 0 0 1 1 -1Z", "M15 3h5a1 1 0 0 1 1 1v3a1 1 0 0 1 -1 1h-5a1 1 0 0 1 -1 -1v-3a1 1 0 0 1 1 -1Z", "M15 12h5a1 1 0 0 1 1 1v7a1 1 0 0 1 -1 1h-5a1 1 0 0 1 -1 -1v-7a1 1 0 0 1 1 -1Z", "M4 16h5a1 1 0 0 1 1 1v3a1 1 0 0 1 -1 1h-5a1 1 0 0 1 -1 -1v-3a1 1 0 0 1 1 -1Z"),
        "lightbulb" to arrayOf("M15 14c.2-1 .7-1.7 1.5-2.5 1-.9 1.5-2.2 1.5-3.5A6 6 0 0 0 6 8c0 1 .2 2.2 1.5 3.5.7.7 1.3 1.5 1.5 2.5", "M9 18h6", "M10 22h4"),
        "lock" to arrayOf("M5 11h14a2 2 0 0 1 2 2v7a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-7a2 2 0 0 1 2 -2Z", "M7 11V7a5 5 0 0 1 10 0v4"),
        "lock-keyhole" to arrayOf("M11 16a1 1 0 1 0 2 0a1 1 0 1 0 -2 0", "M5 10h14a2 2 0 0 1 2 2v8a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-8a2 2 0 0 1 2 -2Z", "M7 10V7a5 5 0 0 1 10 0v3"),
        "log-in" to arrayOf("m10 17 5-5-5-5", "M15 12H3", "M15 3h4a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-4"),
        "log-out" to arrayOf("m16 17 5-5-5-5", "M21 12H9", "M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"),
        "mail" to arrayOf("m22 7-8.991 5.727a2 2 0 0 1-2.009 0L2 7", "M4 4h16a2 2 0 0 1 2 2v12a2 2 0 0 1 -2 2h-16a2 2 0 0 1 -2 -2v-12a2 2 0 0 1 2 -2Z"),
        "minus" to arrayOf("M5 12h14"),
        "moon" to arrayOf("M20.985 12.486a9 9 0 1 1-9.473-9.472c.405-.022.617.46.402.803a6 6 0 0 0 8.268 8.268c.344-.215.825-.004.803.401"),
        "music" to arrayOf("M9 18V5l12-2v13", "M3 18a3 3 0 1 0 6 0a3 3 0 1 0 -6 0", "M15 16a3 3 0 1 0 6 0a3 3 0 1 0 -6 0"),
        "notebook-pen" to arrayOf("M13.4 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-7.4", "M2 6h4", "M2 10h4", "M2 14h4", "M2 18h4", "M21.378 5.626a1 1 0 1 0-3.004-3.004l-5.01 5.012a2 2 0 0 0-.506.854l-.837 2.87a.5.5 0 0 0 .62.62l2.87-.837a2 2 0 0 0 .854-.506z"),
        "palette" to arrayOf("M12 22a1 1 0 0 1 0-20 10 9 0 0 1 10 9 5 5 0 0 1-5 5h-2.25a1.75 1.75 0 0 0-1.4 2.8l.3.4a1.75 1.75 0 0 1-1.4 2.8z", "!M13 6.5a0.5 0.5 0 1 0 1 0a0.5 0.5 0 1 0 -1 0", "!M17 10.5a0.5 0.5 0 1 0 1 0a0.5 0.5 0 1 0 -1 0", "!M6 12.5a0.5 0.5 0 1 0 1 0a0.5 0.5 0 1 0 -1 0", "!M8 7.5a0.5 0.5 0 1 0 1 0a0.5 0.5 0 1 0 -1 0"),
        "party-popper" to arrayOf("M5.8 11.3 2 22l10.7-3.79", "M4 3h.01", "M22 8h.01", "M15 2h.01", "M22 20h.01", "m22 2-2.24.75a2.9 2.9 0 0 0-1.96 3.12c.1.86-.57 1.63-1.45 1.63h-.38c-.86 0-1.6.6-1.76 1.44L14 10", "m22 13-.82-.33c-.86-.34-1.82.2-1.98 1.11c-.11.7-.72 1.22-1.43 1.22H17", "m11 2 .33.82c.34.86-.2 1.82-1.11 1.98C9.52 4.9 9 5.52 9 6.23V7", "M11 13c1.93 1.93 2.83 4.17 2 5-.83.83-3.07-.07-5-2-1.93-1.93-2.83-4.17-2-5 .83-.83 3.07.07 5 2Z"),
        "pause" to arrayOf("M15 3h3a1 1 0 0 1 1 1v16a1 1 0 0 1 -1 1h-3a1 1 0 0 1 -1 -1v-16a1 1 0 0 1 1 -1Z", "M6 3h3a1 1 0 0 1 1 1v16a1 1 0 0 1 -1 1h-3a1 1 0 0 1 -1 -1v-16a1 1 0 0 1 1 -1Z"),
        "paw-print" to arrayOf("M9 4a2 2 0 1 0 4 0a2 2 0 1 0 -4 0", "M16 8a2 2 0 1 0 4 0a2 2 0 1 0 -4 0", "M18 16a2 2 0 1 0 4 0a2 2 0 1 0 -4 0", "M9 10a5 5 0 0 1 5 5v3.5a3.5 3.5 0 0 1-6.84 1.045Q6.52 17.48 4.46 16.84A3.5 3.5 0 0 1 5.5 10Z"),
        "pencil" to arrayOf("M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z", "m15 5 4 4"),
        "piggy-bank" to arrayOf("M11 17h3v2a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1v-3a3.16 3.16 0 0 0 2-2h1a1 1 0 0 0 1-1v-2a1 1 0 0 0-1-1h-1a5 5 0 0 0-2-4V3a4 4 0 0 0-3.2 1.6l-.3.4H11a6 6 0 0 0-6 6v1a5 5 0 0 0 2 4v3a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1z", "M16 10h.01", "M2 8v1a2 2 0 0 0 2 2h1"),
        "pill" to arrayOf("m10.5 20.5 10-10a4.95 4.95 0 1 0-7-7l-10 10a4.95 4.95 0 1 0 7 7Z", "m8.5 8.5 7 7"),
        "plane" to arrayOf("M17.8 19.2 16 11l3.5-3.5C21 6 21.5 4 21 3c-1-.5-3 0-4.5 1.5L13 8 4.8 6.2c-.5-.1-.9.1-1.1.5l-.3.5c-.2.5-.1 1 .3 1.3L9 12l-2 3H4l-1 1 3 2 2 3 1-1v-3l3-2 3.5 5.3c.3.4.8.5 1.3.3l.5-.2c.4-.3.6-.7.5-1.2z"),
        "play" to arrayOf("M5 5a2 2 0 0 1 3.008-1.728l11.997 6.998a2 2 0 0 1 .003 3.458l-12 7A2 2 0 0 1 5 19z"),
        "plus" to arrayOf("M5 12h14", "M12 5v14"),
        "receipt" to arrayOf("M12 17V7", "M16 8h-6a2 2 0 0 0 0 4h4a2 2 0 0 1 0 4H8", "M4 3a1 1 0 0 1 1-1 1.3 1.3 0 0 1 .7.2l.933.6a1.3 1.3 0 0 0 1.4 0l.934-.6a1.3 1.3 0 0 1 1.4 0l.933.6a1.3 1.3 0 0 0 1.4 0l.933-.6a1.3 1.3 0 0 1 1.4 0l.934.6a1.3 1.3 0 0 0 1.4 0l.933-.6A1.3 1.3 0 0 1 19 2a1 1 0 0 1 1 1v18a1 1 0 0 1-1 1 1.3 1.3 0 0 1-.7-.2l-.933-.6a1.3 1.3 0 0 0-1.4 0l-.934.6a1.3 1.3 0 0 1-1.4 0l-.933-.6a1.3 1.3 0 0 0-1.4 0l-.933.6a1.3 1.3 0 0 1-1.4 0l-.934-.6a1.3 1.3 0 0 0-1.4 0l-.933.6a1.3 1.3 0 0 1-.7.2 1 1 0 0 1-1-1z"),
        "repeat" to arrayOf("m17 2 4 4-4 4", "M3 11v-1a4 4 0 0 1 4-4h14", "m7 22-4-4 4-4", "M21 13v1a4 4 0 0 1-4 4H3"),
        "rotate-ccw" to arrayOf("M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8", "M3 3v5h5"),
        "scale" to arrayOf("M12 3v18", "m19 8 3 8a5 5 0 0 1-6 0zV7", "M3 7h1a17 17 0 0 0 8-2 17 17 0 0 0 8 2h1", "m5 8 3 8a5 5 0 0 1-6 0zV7", "M7 21h10"),
        "scissors" to arrayOf("M3 6a3 3 0 1 0 6 0a3 3 0 1 0 -6 0", "M8.12 8.12 12 12", "M20 4 8.12 15.88", "M3 18a3 3 0 1 0 6 0a3 3 0 1 0 -6 0", "M14.8 14.8 20 20"),
        "search" to arrayOf("m21 21-4.34-4.34", "M3 11a8 8 0 1 0 16 0a8 8 0 1 0 -16 0"),
        "settings" to arrayOf("M9.671 4.136a2.34 2.34 0 0 1 4.659 0 2.34 2.34 0 0 0 3.319 1.915 2.34 2.34 0 0 1 2.33 4.033 2.34 2.34 0 0 0 0 3.831 2.34 2.34 0 0 1-2.33 4.033 2.34 2.34 0 0 0-3.319 1.915 2.34 2.34 0 0 1-4.659 0 2.34 2.34 0 0 0-3.32-1.915 2.34 2.34 0 0 1-2.33-4.033 2.34 2.34 0 0 0 0-3.831A2.34 2.34 0 0 1 6.35 6.051a2.34 2.34 0 0 0 3.319-1.915", "M9 12a3 3 0 1 0 6 0a3 3 0 1 0 -6 0"),
        "shield-check" to arrayOf("M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z", "m9 12 2 2 4-4"),
        "shirt" to arrayOf("M20.38 3.46 16 2a4 4 0 0 1-8 0L3.62 3.46a2 2 0 0 0-1.34 2.23l.58 3.47a1 1 0 0 0 .99.84H6v10c0 1.1.9 2 2 2h8a2 2 0 0 0 2-2V10h2.15a1 1 0 0 0 .99-.84l.58-3.47a2 2 0 0 0-1.34-2.23z"),
        "shopping-bag" to arrayOf("M16 10a4 4 0 0 1-8 0", "M3.103 6.034h17.794", "M3.4 5.467a2 2 0 0 0-.4 1.2V20a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6.667a2 2 0 0 0-.4-1.2l-2-2.667A2 2 0 0 0 17 2H7a2 2 0 0 0-1.6.8z"),
        "shopping-cart" to arrayOf("M7 21a1 1 0 1 0 2 0a1 1 0 1 0 -2 0", "M18 21a1 1 0 1 0 2 0a1 1 0 1 0 -2 0", "M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12"),
        "sliders-horizontal" to arrayOf("M10 5H3", "M12 19H3", "M14 3v4", "M16 17v4", "M21 12h-9", "M21 19h-5", "M21 5h-7", "M8 10v4", "M8 12H3"),
        "smartphone" to arrayOf("M7 2h10a2 2 0 0 1 2 2v16a2 2 0 0 1 -2 2h-10a2 2 0 0 1 -2 -2v-16a2 2 0 0 1 2 -2Z", "M12 18h.01"),
        "smile" to arrayOf("M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0", "M8 14s1.5 2 4 2 4-2 4-2", "M9 9L9.01 9", "M15 9L15.01 9"),
        "sparkles" to arrayOf("M11.017 2.814a1 1 0 0 1 1.966 0l1.051 5.558a2 2 0 0 0 1.594 1.594l5.558 1.051a1 1 0 0 1 0 1.966l-5.558 1.051a2 2 0 0 0-1.594 1.594l-1.051 5.558a1 1 0 0 1-1.966 0l-1.051-5.558a2 2 0 0 0-1.594-1.594l-5.558-1.051a1 1 0 0 1 0-1.966l5.558-1.051a2 2 0 0 0 1.594-1.594z", "M20 2v4", "M22 4h-4", "M2 20a2 2 0 1 0 4 0a2 2 0 1 0 -4 0"),
        "split" to arrayOf("M16 3h5v5", "M8 3H3v5", "M12 22v-8.3a4 4 0 0 0-1.172-2.872L3 3", "m15 9 6-6"),
        "square-check-big" to arrayOf("M21 10.656V19a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h12.344", "m9 11 3 3L22 4"),
        "stethoscope" to arrayOf("M11 2v2", "M5 2v2", "M5 3H4a2 2 0 0 0-2 2v4a6 6 0 0 0 12 0V5a2 2 0 0 0-2-2h-1", "M8 15a6 6 0 0 0 12 0v-3", "M18 10a2 2 0 1 0 4 0a2 2 0 1 0 -4 0"),
        "store" to arrayOf("M15 21v-5a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v5", "M17.774 10.31a1.12 1.12 0 0 0-1.549 0 2.5 2.5 0 0 1-3.451 0 1.12 1.12 0 0 0-1.548 0 2.5 2.5 0 0 1-3.452 0 1.12 1.12 0 0 0-1.549 0 2.5 2.5 0 0 1-3.77-3.248l2.889-4.184A2 2 0 0 1 7 2h10a2 2 0 0 1 1.653.873l2.895 4.192a2.5 2.5 0 0 1-3.774 3.244", "M4 10.95V19a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8.05"),
        "table-2" to arrayOf("M9 3H5a2 2 0 0 0-2 2v4m6-6h10a2 2 0 0 1 2 2v4M9 3v18m0 0h10a2 2 0 0 0 2-2V9M9 21H5a2 2 0 0 1-2-2V9m0 0h18"),
        "tag" to arrayOf("M12.586 2.586A2 2 0 0 0 11.172 2H4a2 2 0 0 0-2 2v7.172a2 2 0 0 0 .586 1.414l8.704 8.704a2.426 2.426 0 0 0 3.42 0l6.58-6.58a2.426 2.426 0 0 0 0-3.42z", "!M7 7.5a0.5 0.5 0 1 0 1 0a0.5 0.5 0 1 0 -1 0"),
        "tags" to arrayOf("M13.172 2a2 2 0 0 1 1.414.586l6.71 6.71a2.4 2.4 0 0 1 0 3.408l-4.592 4.592a2.4 2.4 0 0 1-3.408 0l-6.71-6.71A2 2 0 0 1 6 9.172V3a1 1 0 0 1 1-1z", "M2 7v6.172a2 2 0 0 0 .586 1.414l6.71 6.71a2.4 2.4 0 0 0 3.191.193", "!M10 6.5a0.5 0.5 0 1 0 1 0a0.5 0.5 0 1 0 -1 0"),
        "target" to arrayOf("M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0", "M6 12a6 6 0 1 0 12 0a6 6 0 1 0 -12 0", "M10 12a2 2 0 1 0 4 0a2 2 0 1 0 -4 0"),
        "thumbs-up" to arrayOf("M15 5.88 14 10h5.83a2 2 0 0 1 1.92 2.56l-2.33 8A2 2 0 0 1 17.5 22H4a2 2 0 0 1-2-2v-8a2 2 0 0 1 2-2h2.76a2 2 0 0 0 1.79-1.11L12 2a3.13 3.13 0 0 1 3 3.88Z", "M7 10v12"),
        "timer" to arrayOf("M10 2L14 2", "M12 14L15 11", "M4 14a8 8 0 1 0 16 0a8 8 0 1 0 -16 0"),
        "trash-2" to arrayOf("M10 11v6", "M14 11v6", "M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6", "M3 6h18", "M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"),
        "trending-down" to arrayOf("M16 17h6v-6", "m22 17-8.5-8.5-5 5L2 7"),
        "trending-up" to arrayOf("M16 7h6v6", "m22 7-8.5 8.5-5-5L2 17"),
        "triangle-alert" to arrayOf("m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3", "M12 9v4", "M12 17h.01"),
        "trophy" to arrayOf("M10 14.66v1.626a2 2 0 0 1-.976 1.696A5 5 0 0 0 7 21.978", "M14 14.66v1.626a2 2 0 0 0 .976 1.696A5 5 0 0 1 17 21.978", "M18 9h1.5a1 1 0 0 0 0-5H18", "M4 22h16", "M6 9a6 6 0 0 0 12 0V3a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1z", "M6 9H4.5a1 1 0 0 1 0-5H6"),
        "truck" to arrayOf("M14 18V6a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2v11a1 1 0 0 0 1 1h2", "M15 18H9", "M19 18h2a1 1 0 0 0 1-1v-3.65a1 1 0 0 0-.22-.624l-3.48-4.35A1 1 0 0 0 17.52 8H14", "M15 18a2 2 0 1 0 4 0a2 2 0 1 0 -4 0", "M5 18a2 2 0 1 0 4 0a2 2 0 1 0 -4 0"),
        "tv" to arrayOf("m17 2-5 5-5-5", "M4 7h16a2 2 0 0 1 2 2v11a2 2 0 0 1 -2 2h-16a2 2 0 0 1 -2 -2v-11a2 2 0 0 1 2 -2Z"),
        "umbrella" to arrayOf("M12 13v7a2 2 0 0 0 4 0", "M12 2v2", "M20.992 13a1 1 0 0 0 .97-1.274 10.284 10.284 0 0 0-19.923 0A1 1 0 0 0 3 13z"),
        "upload" to arrayOf("M12 3v12", "m17 8-5-5-5 5", "M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"),
        "user" to arrayOf("M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2", "M8 7a4 4 0 1 0 8 0a4 4 0 1 0 -8 0"),
        "user-x" to arrayOf("M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2", "M5 7a4 4 0 1 0 8 0a4 4 0 1 0 -8 0", "M17 8L22 13", "M22 8L17 13"),
        "users" to arrayOf("M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2", "M16 3.128a4 4 0 0 1 0 7.744", "M22 21v-2a4 4 0 0 0-3-3.87", "M5 7a4 4 0 1 0 8 0a4 4 0 1 0 -8 0"),
        "utensils" to arrayOf("M3 2v7c0 1.1.9 2 2 2h4a2 2 0 0 0 2-2V2", "M7 2v20", "M21 15V2a5 5 0 0 0-5 5v6c0 1.1.9 2 2 2h3Zm0 0v7"),
        "wallet" to arrayOf("M19 7V4a1 1 0 0 0-1-1H5a2 2 0 0 0 0 4h15a1 1 0 0 1 1 1v4h-3a2 2 0 0 0 0 4h3a1 1 0 0 0 1-1v-2a1 1 0 0 0-1-1", "M3 5v14a2 2 0 0 0 2 2h15a1 1 0 0 0 1-1v-4"),
        "wand-sparkles" to arrayOf("m21.64 3.64-1.28-1.28a1.21 1.21 0 0 0-1.72 0L2.36 18.64a1.21 1.21 0 0 0 0 1.72l1.28 1.28a1.2 1.2 0 0 0 1.72 0L21.64 5.36a1.2 1.2 0 0 0 0-1.72", "m14 7 3 3", "M5 6v4", "M19 14v4", "M10 2v2", "M7 8H3", "M21 16h-4", "M11 3H9"),
        "wifi" to arrayOf("M12 20h.01", "M2 8.82a15 15 0 0 1 20 0", "M5 12.859a10 10 0 0 1 14 0", "M8.5 16.429a5 5 0 0 1 7 0"),
        "wrench" to arrayOf("M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.106-3.105c.32-.322.863-.22.983.218a6 6 0 0 1-8.259 7.057l-7.91 7.91a1 1 0 0 1-2.999-3l7.91-7.91a6 6 0 0 1 7.057-8.259c.438.12.54.662.219.984z"),
        "x" to arrayOf("M18 6 6 18", "m6 6 12 12"),
        "zap" to arrayOf("M4 14a1 1 0 0 1-.78-1.63l9.9-10.2a.5.5 0 0 1 .86.46l-1.92 6.02A1 1 0 0 0 13 10h7a1 1 0 0 1 .78 1.63l-9.9 10.2a.5.5 0 0 1-.86-.46l1.92-6.02A1 1 0 0 0 11 14z"),
    )

    /** Alternate names (lucide's own renames, e.g. home → house) → canonical icon. */
    private val aliases: Map<String, String> = mapOf(
        "alert-triangle" to "triangle-alert",
        "bar-chart-3" to "chart-column",
        "check-square" to "square-check-big",
        "filter" to "funnel",
        "home" to "house",
        "line-chart" to "chart-line",
        "wand-2" to "wand-sparkles",
    )

    private val cache = ConcurrentHashMap<String, ImageVector>()

    /** Every canonical kebab-case name available. */
    val names: Set<String> get() = data.keys

    /** The icon a kebab-case name refers to (canonical or alias), or null when it is not bundled. */
    fun byKebab(name: String, strokeWidth: Float = 2f): ImageVector? {
        val key = if (data.containsKey(name)) name else aliases[name] ?: return null
        return icon(key, strokeWidth)
    }

    private fun icon(name: String, strokeWidth: Float = 2f): ImageVector =
        cache.getOrPut(if (strokeWidth == 2f) name else "$name@$strokeWidth") {
            build(name, data.getValue(name), strokeWidth)
        }

    private fun build(name: String, paths: Array<String>, strokeWidth: Float): ImageVector {
        val builder = ImageVector.Builder(
            name = "lucide.$name",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        )
        val ink = SolidColor(Color.Black)
        for (raw in paths) {
            val filled = raw.startsWith('!')
            builder.addPath(
                pathData = addPathNodes(if (filled) raw.substring(1) else raw),
                fill = if (filled) ink else null,
                stroke = ink,
                strokeLineWidth = strokeWidth,
                strokeLineCap = StrokeCap.Round,
                strokeLineJoin = StrokeJoin.Round,
            )
        }
        return builder.build()
    }

    val AlertTriangle: ImageVector get() = icon("triangle-alert")
    val Archive: ImageVector get() = icon("archive")
    val ArrowDown: ImageVector get() = icon("arrow-down")
    val ArrowLeft: ImageVector get() = icon("arrow-left")
    val ArrowLeftRight: ImageVector get() = icon("arrow-left-right")
    val ArrowRight: ImageVector get() = icon("arrow-right")
    val ArrowUp: ImageVector get() = icon("arrow-up")
    val Baby: ImageVector get() = icon("baby")
    val Banknote: ImageVector get() = icon("banknote")
    val BarChart3: ImageVector get() = icon("chart-column")
    val Bell: ImageVector get() = icon("bell")
    val BellRing: ImageVector get() = icon("bell-ring")
    val Bike: ImageVector get() = icon("bike")
    val BookmarkPlus: ImageVector get() = icon("bookmark-plus")
    val BookOpen: ImageVector get() = icon("book-open")
    val Briefcase: ImageVector get() = icon("briefcase")
    val Building2: ImageVector get() = icon("building-2")
    val Bus: ImageVector get() = icon("bus")
    val Cake: ImageVector get() = icon("cake")
    val Calendar: ImageVector get() = icon("calendar")
    val CalendarClock: ImageVector get() = icon("calendar-clock")
    val CalendarRange: ImageVector get() = icon("calendar-range")
    val CalendarX: ImageVector get() = icon("calendar-x")
    val Camera: ImageVector get() = icon("camera")
    val Car: ImageVector get() = icon("car")
    val ChartColumn: ImageVector get() = icon("chart-column")
    val ChartLine: ImageVector get() = icon("chart-line")
    val Check: ImageVector get() = icon("check")
    val CheckSquare: ImageVector get() = icon("square-check-big")
    val ChevronDown: ImageVector get() = icon("chevron-down")
    val ChevronLeft: ImageVector get() = icon("chevron-left")
    val ChevronRight: ImageVector get() = icon("chevron-right")
    val ChevronUp: ImageVector get() = icon("chevron-up")
    val CircleAlert: ImageVector get() = icon("circle-alert")
    val CircleCheck: ImageVector get() = icon("circle-check")
    val CircleEllipsis: ImageVector get() = icon("circle-ellipsis")
    val CircleX: ImageVector get() = icon("circle-x")
    val Clock: ImageVector get() = icon("clock")
    val Cloud: ImageVector get() = icon("cloud")
    val CloudUpload: ImageVector get() = icon("cloud-upload")
    val Coffee: ImageVector get() = icon("coffee")
    val Copy: ImageVector get() = icon("copy")
    val CreditCard: ImageVector get() = icon("credit-card")
    val DatabaseBackup: ImageVector get() = icon("database-backup")
    val Delete: ImageVector get() = icon("delete")
    val DollarSign: ImageVector get() = icon("dollar-sign")
    val Download: ImageVector get() = icon("download")
    val Droplet: ImageVector get() = icon("droplet")
    val Dumbbell: ImageVector get() = icon("dumbbell")
    val Eye: ImageVector get() = icon("eye")
    val EyeOff: ImageVector get() = icon("eye-off")
    val FileSpreadsheet: ImageVector get() = icon("file-spreadsheet")
    val FileUp: ImageVector get() = icon("file-up")
    val Film: ImageVector get() = icon("film")
    val Filter: ImageVector get() = icon("funnel")
    val Fingerprint: ImageVector get() = icon("fingerprint-pattern")
    val FingerprintPattern: ImageVector get() = icon("fingerprint-pattern")
    val Flame: ImageVector get() = icon("flame")
    val Folder: ImageVector get() = icon("folder")
    val FolderOpen: ImageVector get() = icon("folder-open")
    val Fuel: ImageVector get() = icon("fuel")
    val Funnel: ImageVector get() = icon("funnel")
    val Gamepad2: ImageVector get() = icon("gamepad-2")
    val Gift: ImageVector get() = icon("gift")
    val GraduationCap: ImageVector get() = icon("graduation-cap")
    val HandCoins: ImageVector get() = icon("hand-coins")
    val Handshake: ImageVector get() = icon("handshake")
    val HardDrive: ImageVector get() = icon("hard-drive")
    val Heart: ImageVector get() = icon("heart")
    val HeartPulse: ImageVector get() = icon("heart-pulse")
    val History: ImageVector get() = icon("history")
    val Home: ImageVector get() = icon("house")
    val House: ImageVector get() = icon("house")
    val Info: ImageVector get() = icon("info")
    val KeyRound: ImageVector get() = icon("key-round")
    val Landmark: ImageVector get() = icon("landmark")
    val Laptop: ImageVector get() = icon("laptop")
    val LayoutDashboard: ImageVector get() = icon("layout-dashboard")
    val Lightbulb: ImageVector get() = icon("lightbulb")
    val LineChart: ImageVector get() = icon("chart-line")
    val Lock: ImageVector get() = icon("lock")
    val LockKeyhole: ImageVector get() = icon("lock-keyhole")
    val LogIn: ImageVector get() = icon("log-in")
    val LogOut: ImageVector get() = icon("log-out")
    val Mail: ImageVector get() = icon("mail")
    val Minus: ImageVector get() = icon("minus")
    val Moon: ImageVector get() = icon("moon")
    val Music: ImageVector get() = icon("music")
    val NotebookPen: ImageVector get() = icon("notebook-pen")
    val Palette: ImageVector get() = icon("palette")
    val PartyPopper: ImageVector get() = icon("party-popper")
    val Pause: ImageVector get() = icon("pause")
    val PawPrint: ImageVector get() = icon("paw-print")
    val Pencil: ImageVector get() = icon("pencil")
    val PiggyBank: ImageVector get() = icon("piggy-bank")
    val Pill: ImageVector get() = icon("pill")
    val Plane: ImageVector get() = icon("plane")
    val Play: ImageVector get() = icon("play")
    val Plus: ImageVector get() = icon("plus")
    val Receipt: ImageVector get() = icon("receipt")
    val Repeat: ImageVector get() = icon("repeat")
    val RotateCcw: ImageVector get() = icon("rotate-ccw")
    val Scale: ImageVector get() = icon("scale")
    val Scissors: ImageVector get() = icon("scissors")
    val Search: ImageVector get() = icon("search")
    val Settings: ImageVector get() = icon("settings")
    val ShieldCheck: ImageVector get() = icon("shield-check")
    val Shirt: ImageVector get() = icon("shirt")
    val ShoppingBag: ImageVector get() = icon("shopping-bag")
    val ShoppingCart: ImageVector get() = icon("shopping-cart")
    val SlidersHorizontal: ImageVector get() = icon("sliders-horizontal")
    val Smartphone: ImageVector get() = icon("smartphone")
    val Smile: ImageVector get() = icon("smile")
    val Sparkles: ImageVector get() = icon("sparkles")
    val Split: ImageVector get() = icon("split")
    val SquareCheckBig: ImageVector get() = icon("square-check-big")
    val Stethoscope: ImageVector get() = icon("stethoscope")
    val Store: ImageVector get() = icon("store")
    val Table2: ImageVector get() = icon("table-2")
    val Tag: ImageVector get() = icon("tag")
    val Tags: ImageVector get() = icon("tags")
    val Target: ImageVector get() = icon("target")
    val ThumbsUp: ImageVector get() = icon("thumbs-up")
    val Timer: ImageVector get() = icon("timer")
    val Trash2: ImageVector get() = icon("trash-2")
    val TrendingDown: ImageVector get() = icon("trending-down")
    val TrendingUp: ImageVector get() = icon("trending-up")
    val TriangleAlert: ImageVector get() = icon("triangle-alert")
    val Trophy: ImageVector get() = icon("trophy")
    val Truck: ImageVector get() = icon("truck")
    val Tv: ImageVector get() = icon("tv")
    val Umbrella: ImageVector get() = icon("umbrella")
    val Upload: ImageVector get() = icon("upload")
    val User: ImageVector get() = icon("user")
    val Users: ImageVector get() = icon("users")
    val UserX: ImageVector get() = icon("user-x")
    val Utensils: ImageVector get() = icon("utensils")
    val Wallet: ImageVector get() = icon("wallet")
    val Wand2: ImageVector get() = icon("wand-sparkles")
    val WandSparkles: ImageVector get() = icon("wand-sparkles")
    val Wifi: ImageVector get() = icon("wifi")
    val Wrench: ImageVector get() = icon("wrench")
    val X: ImageVector get() = icon("x")
    val Zap: ImageVector get() = icon("zap")
}
